name: MasterAction

on:
  push:
    branches:
      - master

jobs:
  bionic-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1.2.0
    - name: Run unit tests
      run: swift test --enable-test-discovery

  release:
    needs: bionic-tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1.2.0
    - name: Release new version
      uses: MatsMoll/action-finch@master
      if: github.ref == 'refs/heads/master'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_REPOSITORY: ${{ secrets.GITHUB_REPOSITORY }}
        GITHUB_SHA: ${{ secrets.GITHUB_SHA }}
        FINCH_CONFIG: CI/finch-config.yml
